on:
  push:
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail to this address
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'ALERT, we have detected a commit in ${{ github.repository }}'
          body: 
            Hello user,

            A commit has been detected!

            Commit created by ${{ github.event.pusher.name }}


          to: "juri.vaitmaa@tthk.ee"
          from: "Github actions for ${{github.repository}}"