on:
  push:
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail to this address
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: stmp.gmail.com
          server_port: 587
          username: $ {{ secrets.MAIL_USERNAME }}
          password: $ {{ secrets.MAIL_PASSWORD }}
          subject: 'ALERT, WE HAVE DETECTED SMTH in YOUR REPO ${{ github.repository }}'
          body: 
            Hello user,

            A commit has been detected in your area.

            Commit created by ${{ github.event.pusher.name }}


          to: "jegorka2002@gmail.com"
          from: "Github actions for ${{github.repository}}"